/* Generated by tools/pack_world.py -- do not edit. */
#ifndef GE_WORLD_LEVELS_H
#define GE_WORLD_LEVELS_H

/* bossGetStageNum() -> the level name the extraction uses. */
typedef struct { int stage; const char *level; } GeWorldStageName;

static const GeWorldStageName ge_world_stage_names[] = {
    { 9, "bunker1" },
    { 20, "silo" },
    { 22, "statue" },
    { 23, "control" },
    { 24, "archives" },
    { 25, "train" },
    { 26, "frigate" },
    { 27, "bunker2" },
    { 28, "aztec" },
    { 29, "streets" },
    { 30, "depot" },
    { 31, "complex" },
    { 32, "egypt" },
    { 33, "dam" },
    { 34, "facility" },
    { 35, "runway" },
    { 36, "surface" },
    { 37, "jungle" },
    { 38, "temple" },
    { 39, "caverns" },
    { 41, "cradle" },
    { 43, "surface2" },
    { 45, "basement" },
    { 46, "stack" },
    { 48, "library" },
    { 50, "caves" },
};
#define GE_WORLD_STAGE_COUNT 26

#endif /* GE_WORLD_LEVELS_H */
