#!/usr/bin/env python3
"""
Audit N64 struct layouts against the offsets the decomp documents in comments.

The decomp annotates most struct members with their N64 byte offset, e.g.

    s32 *rooms;         /* 0x00 */
    /*0x044*/ struct Projectile *projectile;

On the N64 a pointer is 4 bytes; on arm64 it is 8. So any struct holding a pointer
silently changes shape, and code that indexes such a record by word (GoldenEye does
this in several places) reads the wrong field. That class of bug does NOT show up as
a compile error -- it corrupts at runtime -- so it needs its own check.

This emits a _Static_assert(offsetof(...) == ...) for every documented member and
compiles it, turning the comments into enforced invariants.

Run from the decomp root (vendor/ge-decomp):
    python3 ../../tools/audit_struct_layout.py
"""
import io
import os
import re
import subprocess
import sys

HEADERS = ['src/bondtypes.h']
OUT = 'src/ge_layout_audit.c'

SDK = subprocess.run(['xcrun', '-sdk', 'appletvos', '--show-sdk-path'],
                     capture_output=True, text=True).stdout.strip()

FLAGS = ['-target', 'arm64-apple-tvos17.0', '-isysroot', SDK, '-fsyntax-only',
         '-fms-extensions', '-include', 'src/ge_port_decls.h',
         '-I', '.', '-I', 'include', '-I', 'include/PR', '-I', 'src',
         '-I', 'src/game', '-I', 'src/inflate',
         '-DVERSION_US', '-DLANG_US', '-DREFRESH_NTSC', '-DLEFTOVERDEBUG',
         '-DLEFTOVERSPECTRUM', '-DBUGFIX_R0', '-DTARGET_N64', '-DGE_PORT_NATIVE',
         '-DNON_MATCHING=1', '-DAVOID_UB=1', '-D_LANGUAGE_C=1',
         '-w', '-ferror-limit=0']

STRUCT_OPEN = re.compile(r'^\s*(?:typedef\s+)?struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*$')
STRUCT_OPEN_BRACE = re.compile(r'^\s*(?:typedef\s+)?struct\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{')

LEAD_OFF = re.compile(r'^\s*/\*\s*(0x[0-9A-Fa-f]+)\s*\*/\s*(.+)$')
TRAIL_OFF = re.compile(r'^(.*?;)\s*(?://|/\*)\s*(0x[0-9A-Fa-f]+)')

# `s32 count;` / `u8 *bitStream;` / `Mtxf matrix;` / `s8 age[4];`
MEMBER = re.compile(r'^\s*[A-Za-z_][A-Za-z0-9_ \t\*]*?[ \t\*]'
                    r'([A-Za-z_][A-Za-z0-9_]*)\s*(?:\[[^\]]*\])?\s*;\s*$')


def parse(path):
    """Yield (struct_name, member, documented_offset) for depth-1 members."""
    lines = io.open(path, encoding='utf-8', errors='surrogateescape').read().split('\n')
    name, depth = None, 0
    for i, raw in enumerate(lines):
        if name is None:
            m = STRUCT_OPEN_BRACE.match(raw)
            if m:
                name, depth = m.group(1), raw.count('{') - raw.count('}')
                continue
            m = STRUCT_OPEN.match(raw)
            if m and i + 1 < len(lines) and lines[i + 1].strip().startswith('{'):
                name, depth = m.group(1), 0
            continue

        depth += raw.count('{') - raw.count('}')
        if depth <= 0:
            name = None
            continue
        if depth != 1:
            continue          # inside a nested struct/union - offsets are relative

        line, off = raw, None
        m = LEAD_OFF.match(raw)
        if m:
            off, line = m.group(1), m.group(2)
        else:
            m = TRAIL_OFF.match(raw)
            if m:
                line, off = m.group(1), m.group(2)
        if off is None:
            continue
        # strip any inline comment left in the declaration
        line = re.sub(r'/\*.*?\*/', '', line)
        mm = MEMBER.match(line)
        if not mm:
            continue          # function pointers, bitfields, `inherits X;`
        yield name, mm.group(1), int(off, 16)


def main():
    entries = []
    for h in HEADERS:
        entries += list(parse(h))
    if not entries:
        print('no documented offsets parsed'); return 1

    # NOT offsetof(): the decomp ships its own include/stddef.h, and by the time this
    # TU is compiled the system headers pulled in by ge_port_decls.h have already
    # tripped the include guard, so NEITHER definition lands and every assertion
    # silently fails to parse instead of evaluating. __builtin_offsetof needs no header.
    out = ['/* GENERATED by tools/audit_struct_layout.py - do not edit, do not commit.',
           ' * Turns the decomp\'s documented N64 offsets into enforced invariants. */',
           '']
    for s, m, off in entries:
        out.append('_Static_assert(__builtin_offsetof(struct %s, %s) == %d, "%s.%s moved");'
                   % (s, m, off, s, m))
    io.open(OUT, 'w', encoding='utf-8', errors='surrogateescape').write('\n'.join(out) + '\n')
    print('emitted %d offset assertions across %d structs'
          % (len(entries), len({e[0] for e in entries})))

    def failures(target):
        flags = ['-target', target] + FLAGS[2:]
        r = subprocess.run(['clang'] + flags + [OUT], capture_output=True, text=True)
        out = (r.stdout + r.stderr).split('\n')
        got = set()
        for line in out:
            if 'static assertion failed' in line or 'static_assert failed' in line:
                m = re.search(r'([A-Za-z0-9_]+)\.([A-Za-z0-9_]+) moved\s*$', line)
                if m:
                    got.add('%s.%s' % (m.group(1), m.group(2)))
        return got, out

    # A 32-bit ABI has 4-byte pointers, same as the N64. Anything that fails THERE is
    # a wrong comment in the decomp, not a port problem. Anything that passes at
    # 32-bit but fails at 64-bit is a genuine pointer-width layout shift.
    bad32, _ = failures('armv7-apple-ios10.0')
    bad64, errs = failures(FLAGS[1])
    hazards = bad64 - bad32
    print('\n%d members fail at 32-bit too -> the decomp comment is wrong, not a port bug'
          % len(bad32))
    print('%d members are correct at 32-bit and WRONG at 64-bit -> real port hazards'
          % len(hazards))

    # clang prints:  error: static assertion failed due to requirement '...': Name.field moved
    # The message comes after the final colon and is NOT quoted.
    moved, unknown = [], 0
    for line in errs:
        if 'static assertion failed' in line or 'static_assert failed' in line:
            m = re.search(r'([A-Za-z0-9_]+)\.([A-Za-z0-9_]+) moved\s*$', line)
            if m:
                moved.append('%s.%s' % (m.group(1), m.group(2)))
        elif 'error:' in line and 'moved' not in line:
            unknown += 1

    # Once one member shifts, every later member in the same struct shifts too, so
    # only the FIRST offender in each struct is a distinct root cause.
    order = {}
    for idx, (s, m, off) in enumerate(entries):
        order[(s, m)] = (idx, off)
    by_struct = {}
    for s, m, off in entries:
        if '%s.%s' % (s, m) in hazards:
            by_struct.setdefault(s, []).append((off, m))

    print('\n=== %d of %d structs carry a real 64-bit layout hazard ===' % (
        len(by_struct), len({e[0] for e in entries})))
    print('=== showing the FIRST member to shift in each ===\n')
    rows = sorted(by_struct.items(), key=lambda kv: -len(kv[1]))
    for s, members in rows:
        off, m = min(members)
        print('  %-38s first shift at %-7s %-24s (+%d more)'
              % (s, hex(off), m, len(members) - 1))
    if unknown:
        print('\n(%d other errors in the audit TU - check src/ge_layout_audit.c)' % unknown)
    return 0


if __name__ == '__main__':
    sys.exit(main())
