#!/usr/bin/env bash
# Does every patch in getv/patches still apply to a tree that has only just been cloned?
#
# This exists because the answer has been "no" three separate times, and every one of them was
# found by a person running a fresh install rather than by anything in the repository:
#
#   issue #4   0003, 0004 and 0005 were folded into 0001 and nobody retired them, so applying
#              them on top of 0001 tried to add lines that were already there.
#   issue #5   0006 was regenerated by hand and one context line was truncated, so git apply
#              refused it and the tree it was meant to fix would not link.
#   0012       regenerated against a tree that already had the previous version of itself
#              applied, so its context lines carried its own added code. v1 and v2 of the same
#              patch applied fine; only the final one did not.
#
# All three are invisible from a working tree, because a working tree already has the changes.
# That is the whole difficulty: the machine that made the mistake is the one machine that cannot
# see it. So this clones a pristine decomp and applies the patches to that instead.
#
# 0002 is not checked. It patches files that a fresh checkout does not have -- they are generated
# from the ROM by the asset pipeline -- so there is nothing here to apply it to without running
# the whole of docs/SETUP.md section 3.5 first. tools/install.sh covers it in place.
#
# Usage:  bash tools/check_patches.sh          exit 0 if every patch applies
#         GETV_KEEP=1 bash tools/check_patches.sh    leave the scratch tree for inspection
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PATCHDIR="$ROOT/getv/patches"
UPSTREAM="https://github.com/n64decomp/007"
fail=0

say()  { printf '%s\n' "$*"; }
bad()  { printf '  FAIL  %s\n' "$*"; fail=1; }
good() { printf '  ok    %s\n' "$*"; }

# A local clone is preferred over the network: it is faster, it works offline, and a clone takes
# only committed state, so a vendor tree with every patch already applied still yields a pristine
# one. If there is no local decomp, fall back to upstream.
SCRATCH="$(mktemp -d)"
trap '[ -n "${GETV_KEEP:-}" ] || rm -rf "$SCRATCH"' EXIT
DECOMP="$SCRATCH/ge-decomp"

if [ -d "$ROOT/vendor/ge-decomp/.git" ]; then
    say "cloning a pristine decomp from vendor/ge-decomp"
    git clone -q "$ROOT/vendor/ge-decomp" "$DECOMP" || { say "clone failed"; exit 1; }
else
    say "no local decomp; cloning $UPSTREAM (this is the slow path)"
    git clone -q --depth 1 "$UPSTREAM" "$DECOMP" || { say "clone failed"; exit 1; }
fi

# Prove the clone is actually pristine before trusting anything measured against it. A dirty
# scratch tree would make every patch look fine for the wrong reason.
if [ -n "$(git -C "$DECOMP" status --porcelain)" ]; then
    say "the scratch clone is not clean; refusing to report on it"
    exit 1
fi

say ""
say "applying every patch in numeric order, to a tree nobody has touched"

shopt -s nullglob
patches=("$PATCHDIR"/0*.patch)
if [ ${#patches[@]} -eq 0 ]; then
    say "no patches found in $PATCHDIR -- that is itself wrong"
    exit 1
fi

checked=0
for p in "${patches[@]}"; do
    name="$(basename "$p")"
    case "$name" in
        0002-*) say "  skip  $name (needs generated assets; install.sh covers it)"; continue ;;
    esac
    if ( cd "$DECOMP" && git apply "$p" ) 2>"$SCRATCH/err"; then
        good "$name"
        checked=$((checked + 1))
    else
        bad "$name"
        sed 's/^/          /' "$SCRATCH/err" | head -6
    fi
done

# A count of zero would mean the loop never ran and the whole thing reported success by
# accident, which is the failure mode this script exists to catch in other people's work.
if [ "$checked" -eq 0 ]; then
    say ""
    say "no patches were actually applied -- treating that as a failure, not a pass"
    exit 1
fi

# Second check, a different bug with the same shape. A patch that is committed but never named
# by a setup script is invisible: the tree builds, nothing complains, and the change is simply
# absent. That has happened to 0003 and then to 0007.
say ""
say "checking every patch is registered in the setup scripts"
for p in "${patches[@]}"; do
    name="$(basename "$p")"
    case "$name" in 0002-*) continue ;; esac
    missing=""
    for s in setup.sh setup-mac.sh setup-windows.sh; do
        [ -f "$ROOT/tools/$s" ] || continue
        grep -q "$name" "$ROOT/tools/$s" || grep -q "${name%.patch}" "$ROOT/tools/$s" || missing="$missing $s"
    done
    if [ -n "$missing" ]; then
        bad "$name is not named in:$missing"
    else
        good "$name registered"
    fi
done

say ""
if [ "$fail" -eq 0 ]; then
    say "all $checked patches apply to a fresh checkout and are registered"
else
    say "see getv/patches/README.md; a patch that does not apply to a fresh clone stops"
    say "tools/install.sh dead for everyone who is not working from an existing tree"
fi
[ -n "${GETV_KEEP:-}" ] && say "scratch tree kept at $SCRATCH"
exit "$fail"
