#!/usr/bin/env python3
"""
Emit GoldenEye's obseg model blobs as C byte arrays.

Why this exists
---------------
`assets/obseg/ob_seg.s` defines every character/prop/gun model as a global label
followed by `.incbin "build/u/assets/obseg/<path>/<name>.rz"`. The game's resource
table (file_resource_table.inc.c) references those labels, loads the blob, and
inflates it at runtime.

The port builds only .c, so those 725 symbols do not exist natively. Rather than change
the game's load and inflate path, this emits the same bytes as C arrays under the same
names, so the game behaves as it did on hardware.

The compression
---------------
Rare's "1172" container is the two magic bytes 0x11 0x72 followed by a raw deflate
stream, i.e. gzip output with its 10-byte header and 8-byte CRC/size trailer removed.
tools/1172compress.sh does this with `gzip | tail --bytes=+11 | head --bytes=-8`.

That script does not run on macOS: BSD `head` has no `--bytes=-8` (drop trailing N).
This does the same thing in Python, which is portable and avoids ~725 subprocess round
trips.

Run from the decomp root (vendor/ge-decomp):
    python3 ../../tools/gen_obseg_blobs.py
"""
import gzip
import io
import os
import re
import sys

OB_SEG = 'assets/obseg/ob_seg.s'
OUT = 'assets/obseg/ge_obseg_blobs.c'
BYTES_PER_LINE = 16


def rare_1172(raw):
    """gzip, then strip the 10-byte header and 8-byte trailer, behind the magic."""
    buf = io.BytesIO()
    # mtime=0 matches --no-name: no filename/timestamp, so the header is exactly 10 bytes.
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=9, mtime=0) as gz:
        gz.write(raw)
    comp = buf.getvalue()
    assert comp[:2] == b'\x1f\x8b', 'unexpected gzip magic'
    return b'\x11\x72' + comp[10:-8]


def entries():
    """(path, symbol, compress) for every blob ob_seg.s would .incbin.

    There are two macro families, and they differ in more than name.

    `obseg_file_rz` / `obseg_file_Z` incbin a `.rz`, which is a 1172 container, so those
    blobs get compressed here.

    `bg_file_seg` incbins a `.seg`, which is the raw level segment. Its point tables are
    individually 1172-compressed inside it (bg_dam alone has 337 embedded 0x1172 headers,
    inflated one room at a time by bgDecompress), and filelist.u.csv marks every bg row
    compressed=0. Wrapping the whole segment in another 1172 layer would be wrong: the
    game reads a room-position table straight off the front of it.

    Missing this second family is why bg was silently absent. A regex matching only
    obseg_file_* skips all 34 bg segments without a word, every bg_*_all_p_seg resolves
    to a 256 KB 0xFF link stub, and gePortObsegSize returns 0 -- which makes
    obLoadBGFileBytesAtOffset take its `if (rom_size != 0)` branch and do nothing,
    silently, leaving load_bg_file parsing an uninitialised header.
    """
    text = io.open(OB_SEG, encoding='utf-8', errors='surrogateescape').read()
    for m in re.finditer(r'^\s*obseg_file_(?:rz|Z)\s+(\w+)\s*,\s*(\w+)\s*$', text, re.M):
        yield m.group(1), m.group(2), True       # (path, symbol, compress)
    for m in re.finditer(r'^\s*bg_file_seg\s+(\w+)\s*,\s*(\w+)\s*$', text, re.M):
        # symbol is bg_X_all_p_seg; the .bin on disk is named after the SECOND arg.
        yield 'bg', m.group(1), False, m.group(2)


def main():
    out = [
        '/* GENERATED by tools/gen_obseg_blobs.py - do not edit, do not commit.',
        ' *',
        ' * The obseg model blobs that ob_seg.s would .incbin. Same bytes, same symbol',
        ' * names, so the game\'s resource table and its runtime inflate path work',
        ' * unchanged. Regenerate after re-extracting assets from the ROM. */',
        '',
    ]
    found = missing = 0
    missing_names = []

    sizes = []
    for ent in entries():
        if len(ent) == 4:
            path, sym, compress, srcname = ent
        else:
            path, sym, compress = ent
            srcname = sym
        src = os.path.join('assets', 'obseg', path, srcname + '.bin')
        if not os.path.exists(src) or os.path.getsize(src) == 0:
            missing += 1
            missing_names.append(sym)
            continue
        raw = io.open(src, 'rb').read()
        blob = rare_1172(raw) if compress else raw
        sizes.append((sym, len(blob)))
        out.append('/* %s/%s: %d raw -> %d packed */' % (path, sym, len(raw), len(blob)))
        out.append('unsigned char %s[%d] = {' % (sym, len(blob)))
        for i in range(0, len(blob), BYTES_PER_LINE):
            chunk = blob[i:i + BYTES_PER_LINE]
            out.append('    ' + ','.join('0x%02x' % b for b in chunk) + ',')
        out.append('};')
        out.append('')
        found += 1

    io.open(OUT, 'w', encoding='utf-8').write('\n'.join(out) + '\n')

    # gePortObsegSize() looks sizes up by address; without an entry it returns 0, and a
    # 0 size makes the loader silently skip the file. Emit the bg half here so the two
    # generated files cannot drift apart.
    bgs = [(n, sz) for n, sz in sizes if n.startswith('bg_')]
    if bgs:
        sz_out = ['/* GENERATED by tools/gen_obseg_blobs.py - bg segment sizes.',
                  ' * Included by ge_obseg_sizes.c so gePortObsegSize() can resolve them. */',
                  '']
        for n, _ in bgs:
            sz_out.append('extern unsigned char %s[];' % n)
        sz_out.append('')
        sz_out.append('#define GE_OBSEG_BG_SIZES \\')
        for n, sz in bgs:
            sz_out.append('    { %s, %uu }, \\' % (n, sz))
        sz_out.append('    /* end */')
        io.open('assets/obseg/ge_obseg_bg_sizes.h', 'w').write('\n'.join(sz_out) + '\n')
        print('emitted %d bg sizes -> assets/obseg/ge_obseg_bg_sizes.h' % len(bgs))
    # The other half of the same table. fileInit() sizes a resource by subtracting its
    # hw_address from the next entry's, which was exact on the N64 because every file sat
    # contiguously in ROM. Here each blob is a separately linked C array, so the linker
    # orders and pads them as it pleases and that subtraction returns nonsense -- for LgunE
    # it produced 0xFFFFCC00, which sent load_resource() reading far past its buffer.
    # PlegalpageZ happened to come out right purely by adjacency, which is what made the
    # bug look intermittent. gePortObsegSize() replaces the subtraction with a lookup, so
    # the real sizes have to be recorded, and recorded from the same run that wrote the
    # blobs or the two drift.
    nonbg = sorted((n, sz) for n, sz in sizes if not n.startswith('bg_'))
    if nonbg:
        c_out = [
            '/* GENERATED by tools/gen_obseg_blobs.py - do not edit, do not commit.',
            ' *',
            ' * True byte sizes for the obseg blobs, keyed by address. See gePortObsegSize()',
            ' * at the bottom of this file for why the game cannot derive them itself. */',
            '#include <ultra64.h>',
            '',
        ]
        for n, _ in nonbg:
            c_out.append('extern unsigned char %s[];' % n)
        c_out += [
            '',
            '/* The bg level segments, emitted by the same run into ge_obseg_bg_sizes.h so the',
            ' * two cannot drift. Some bg_file_seg entries have no blob: the levels cut during',
            ' * development carry size 0 in filelist.u.csv, with offsets pointing at the start',
            ' * of the following section. Their absence is correct, not a failed extraction. */',
            '#include "ge_obseg_bg_sizes.h"',
            '',
            'static const struct { const void *addr; unsigned int size; } ge_obseg_sizes[] = {',
            '    GE_OBSEG_BG_SIZES',
        ]
        for n, sz in nonbg:
            c_out.append('    { %s, %uu },' % (n, sz))
        c_out += [
            '};',
            '',
            "/* Returns the blob's true byte size, or 0 if the address is not a known blob. */",
            'unsigned int gePortObsegSize(const void *addr)',
            '{',
            '    unsigned int i;',
            '    if (addr == 0) {',
            '        return 0;',
            '    }',
            '    for (i = 0; i < sizeof(ge_obseg_sizes) / sizeof(ge_obseg_sizes[0]); i++) {',
            '        if (ge_obseg_sizes[i].addr == addr) {',
            '            return ge_obseg_sizes[i].size;',
            '        }',
            '    }',
            '    return 0;',
            '}',
        ]
        io.open('assets/obseg/ge_obseg_sizes.c', 'w', encoding='utf-8').write('\n'.join(c_out) + '\n')
        print('emitted %d blob sizes -> assets/obseg/ge_obseg_sizes.c' % len(nonbg))

    size = os.path.getsize(OUT)
    print('emitted %d blobs -> %s (%.1f MB)' % (found, OUT, size / 1048576.0))
    if missing:
        print('%d had no .bin (re-extract from the ROM to get them):' % missing)
        print('  ' + ' '.join(missing_names[:12]) + (' ...' if missing > 12 else ''))
    return 0


if __name__ == '__main__':
    sys.exit(main())
