#!/usr/bin/env python3
"""
Emit the animation DATA and ENTRIES segments as contiguous C blobs.

Why this exists
---------------
alloc_load_expand_ani_table() romCopy()s one contiguous animation-data segment out of
ROM, then walks animation_table_ptrs1/2 -- arrays of byte offsets into that segment --
turning each into a pointer. The offsets are the PTR_ANIM_* / PTR_ANIM_ENTRY_* defines.

The decomp extracts the same data as many separate C arrays (ANIM_DATA_x[],
ANIM_ENTRY_x[]), which have no defined relative placement once compiled. So the port
needs the segment rebuilt as one array, in ROM order.

Byte order is the subtle part. The arrays hold u32 values read from a big-endian ROM,
and the animation payload is read byte-wise (ModelAnimation.bitStream is a u8*), so the
blob must reproduce the original byte stream, i.e. each u32 emitted big-endian. Emitting
native little-endian words would scramble every bitstream while leaving the u32-sized
header fields looking correct.

Verification
------------
Concatenating in declaration order is a hypothesis. The PTR_ANIM_* defines say where
each array is supposed to start, so every one is checked. If they all agree, the blob is
in ROM order; if any disagrees the tool refuses to write.

Run from the decomp root (vendor/ge-decomp):
    python3 ../../tools/gen_anim_blobs.py
"""
import io
import re
import sys

SETS = [
    # (data .c, defines .h, define prefix, array prefix, blob symbol, output)
    ('assets/animationtable_data.c',    'assets/animationtable_data.h',
     'PTR_ANIM_', 'ANIM_DATA_', 'ge_animation_data_segment',
     'assets/ge_animation_data_segment.c'),
    ('assets/animationtable_entries.c', 'assets/animationtable_entries.h',
     'PTR_ANIM_ENTRY_', 'ANIM_ENTRY_', 'ge_animation_entries_segment',
     'assets/ge_animation_entries_segment.c'),
]

ARRAY = re.compile(r'^u32\s+([A-Za-z_][A-Za-z0-9_]*)\s*\[\s*\]\s*=\s*\{(.*?)\};',
                   re.S | re.M)


def load_defines(path, prefix):
    out = {}
    for line in io.open(path, encoding='utf-8', errors='surrogateescape'):
        m = re.match(r'\s*#define\s+(%s[A-Za-z0-9_]*)\s+(0x[0-9A-Fa-f]+|\d+)\s*$'
                     % re.escape(prefix), line)
        if m:
            out[m.group(1)] = int(m.group(2), 0)
    return out


def parse_arrays(path, defines_all):
    """Return [(name, [u32 words])] in file order."""
    text = io.open(path, encoding='utf-8', errors='surrogateescape').read()
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
    text = re.sub(r'//[^\n]*', '', text)
    out = []
    for m in ARRAY.finditer(text):
        words = []
        for tok in m.group(2).split(','):
            tok = tok.strip()
            if not tok:
                continue
            if re.match(r'^0[xX][0-9A-Fa-f]+$', tok):
                words.append(int(tok, 16) & 0xFFFFFFFF)
            elif re.match(r'^-?\d+$', tok):
                words.append(int(tok) & 0xFFFFFFFF)
            elif tok in defines_all:
                words.append(defines_all[tok] & 0xFFFFFFFF)
            else:
                raise SystemExit('unresolved token %r in %s (%s)'
                                 % (tok, path, m.group(1)))
        out.append((m.group(1), words))
    return out


def main():
    all_defines = {}
    for _, hdr, pfx, _, _, _ in SETS:
        all_defines.update(load_defines(hdr, pfx))

    ok = True
    for src, hdr, pfx, apfx, sym, out in SETS:
        arrays = parse_arrays(src, all_defines)
        defs = load_defines(hdr, pfx)

        blob, offsets = bytearray(), {}
        for name, words in arrays:
            offsets[name] = len(blob)
            for w in words:
                blob += w.to_bytes(4, 'big')      # ROM byte order -- see module docstring

        checked = missing = bad = 0
        for name, off in offsets.items():
            if not name.startswith(apfx):
                continue
            want = defs.get(pfx + name[len(apfx):])
            if want is None:
                missing += 1
                continue
            checked += 1
            if want != off:
                bad += 1
                if bad <= 5:
                    print('  MISMATCH %s: define says 0x%X, concatenation gives 0x%X'
                          % (name, want, off))
        print('%s: %d arrays, %d bytes; %d offsets checked, %d mismatched, %d had no define'
              % (src, len(arrays), len(blob), checked, bad, missing))
        if bad:
            ok = False
            continue

        with io.open(out, 'w', encoding='utf-8') as f:
            f.write('/* GENERATED by tools/gen_anim_blobs.py - do not edit by hand.\n'
                    ' *\n'
                    ' * %s rebuilt as ONE contiguous array in ROM order, so the\n'
                    ' * PTR_%s* byte offsets resolve. Stored BIG-ENDIAN: the animation\n'
                    ' * payload is read byte-wise through ModelAnimation.bitStream, so the\n'
                    ' * original byte stream has to survive. All %d offsets verified against\n'
                    ' * the generated defines. */\n'
                    'unsigned char %s[] = {\n' % (src, apfx, checked, sym))
            for i in range(0, len(blob), 16):
                f.write('    ' + ','.join('0x%02x' % b for b in blob[i:i + 16]) + ',\n')
            f.write('};\n'
                    'const unsigned int %s_size = %du;\n' % (sym, len(blob)))

            # Compile-time symbol-to-offset defines.
            #
            # The game reaches animations two ways: by PTR_ANIM_* byte offset, and by
            # taking a symbol's address (`ANIM_PTR(ANIM_DATA_walking)`). On the N64 the
            # second form worked because ANIM_DATA_* were fake linker symbols whose
            # address was the offset.
            #
            # Here those symbols are not linked at all: assets/animationtable_data.c does
            # not compile, so they resolve to poisoned link stubs and ANIM_PTR() hands out
            # garbage. Emitting the offset as a macro per symbol removes the need for the
            # symbol entirely: it is resolved at compile time, costs nothing at runtime,
            # and cannot silently point at a stub.
            if apfx == 'ANIM_DATA_':
                hdr_out = 'assets/ge_animation_offsets.h'
                mapped = [(n, offsets[n]) for n, _ in arrays
                          if (pfx + n[len(apfx):]) in defs]
                with io.open(hdr_out, 'w', encoding='utf-8') as h:
                    h.write('/* GENERATED by tools/gen_anim_blobs.py - do not edit.\n'
                            ' *\n'
                            ' * GE_ANIMOFF_<symbol> = that animation\'s byte offset into the\n'
                            ' * animation-data segment. Use instead of &<symbol>, which on the\n'
                            ' * N64 encoded the offset in the address but here does not exist. */\n'
                            '#ifndef GE_ANIMATION_OFFSETS_H\n#define GE_ANIMATION_OFFSETS_H\n\n')
                    for n, o in mapped:
                        h.write('#define GE_ANIMOFF_%s 0x%Xu\n' % (n, o))
                    h.write('\n#endif\n')
                print('  -> %s (%d symbols)' % (hdr_out, len(mapped)))

        print('  -> %s (%s, %d bytes)' % (out, sym, len(blob)))

    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
