#!/usr/bin/env python3
"""
Regenerate src/ge_port_decls.h for the tvOS port.

IDO accepted implicit function declarations; C99+/clang does not, and that alone
accounted for ~657 errors across 351 functions. Silencing the warning is NOT an
option: an implicit `int` return corrupts pointer- and float-returning functions
on arm64. So this extracts each prototype verbatim from the real definition.

Run from the decomp root (vendor/ge-decomp):
    python3 ../../tools/gen_port_decls.py
"""
import io
import os
import re
import subprocess
import sys

OUT = 'src/ge_port_decls.h'

# Headers that are NOT self-contained and break when force-included.
HEADER_DENYLIST = {'bondview_internal.h', 'zlib.h'}

SDK = subprocess.run(['xcrun', '-sdk', 'appletvos', '--show-sdk-path'],
                     capture_output=True, text=True).stdout.strip()

FLAGS = ['-target', 'arm64-apple-tvos17.0', '-isysroot', SDK, '-fsyntax-only',
         '-fms-extensions',
         '-I', '.', '-I', 'include', '-I', 'include/PR', '-I', 'src',
         '-I', 'src/game', '-I', 'src/inflate',
         '-DVERSION_US', '-DLANG_US', '-DREFRESH_NTSC', '-DLEFTOVERDEBUG',
         '-DLEFTOVERSPECTRUM', '-DBUGFIX_R0', '-DTARGET_N64', '-DGE_PORT_NATIVE',
         '-DNON_MATCHING=1', '-DAVOID_UB=1', '-D_LANGUAGE_C=1',
         '-w', '-ferror-limit=0']

# A definition is `<ret> name(args)` with `{` on the same line or the next one.
DEFN = re.compile(r'^([A-Za-z_][A-Za-z0-9_ \t\*]*?[ \t\*])'
                  r'([A-Za-z_][A-Za-z0-9_]*)\s*\((.*)\)\s*\{?\s*$')


def sources():
    for root, _, files in os.walk('src'):
        for f in sorted(files):
            if f.endswith('.c'):
                yield os.path.join(root, f)


def undeclared_names():
    """Sweep the game sources and collect implicitly-declared functions."""
    names = set()
    for path in sources():
        r = subprocess.run(['clang'] + FLAGS + [path], capture_output=True, text=True)
        names |= set(re.findall(r"call to undeclared (?:library )?function '([A-Za-z0-9_]+)'",
                                r.stdout + r.stderr))
    return names


def extract(names):
    found = {}
    for path in sources():
        lines = io.open(path, encoding='utf-8', errors='surrogateescape').read().split('\n')
        for i, ln in enumerate(lines):
            if not ln or ln[0] in ' \t#/}':
                continue
            m = DEFN.match(ln)
            if not m:
                continue
            nxt = lines[i + 1].strip() if i + 1 < len(lines) else ''
            if not ln.rstrip().endswith('{') and not nxt.startswith('{'):
                continue
            ret, name, args = m.group(1).strip(), m.group(2), m.group(3)
            if name in names and name not in found:
                found[name] = 'extern %s %s(%s);' % (ret, name, args)
    return found


def game_headers():
    hdrs = ['bondtypes.h', 'bondconstants.h']
    for root, _, files in os.walk('src/game'):
        for f in sorted(files):
            if f.endswith('.h') and f not in HEADER_DENYLIST:
                hdrs.append(os.path.relpath(os.path.join(root, f), 'src'))
    return hdrs


def write(hdrs, protos):
    out = [
        '/* GENERATED by tools/gen_port_decls.py - do not edit by hand.',
        ' *',
        ' * IDO accepted implicit function declarations; C99+/clang does not. Every',
        ' * prototype below is extracted verbatim from the real definition, because an',
        ' * implicit int return would corrupt pointer- and float-returning functions on',
        ' * arm64. This header is force-included via -include. */',
        '#ifndef GE_PORT_DECLS_H',
        '#define GE_PORT_DECLS_H',
        '',
        '/* The N64 build got these from IDO implicitly. */',
        '#include <string.h>',
        '#include <stdlib.h>',
        '',
    ]
    out += ['#include "%s"' % h for h in hdrs]

    # A struct tag first named inside a prototype's parameter list has PROTOTYPE
    # scope, so it is a different type from a file-scope struct of the same name
    # declared later (e.g. StanPrefixRecord, defined only inside stan.c). That
    # shows up as "conflicting types". Forward-declare every tag at file scope.
    tags = set()
    for p in protos:
        tags |= set(re.findall(r'\bstruct\s+([A-Za-z_][A-Za-z0-9_]*)', p))
    if tags:
        out += ['', '/* File-scope forward declarations: a struct tag first named in a',
                ' * prototype parameter list would otherwise have prototype scope. */']
        out += ['struct %s;' % t for t in sorted(tags)]

    out += [''] + protos + ['', '#endif', '']
    io.open(OUT, 'w', encoding='utf-8', errors='surrogateescape').write('\n'.join(out))


def main():
    # This regenerates OUT from scratch. 0001-source.patch installs a curated version of
    # the same header, and regenerating over it silently reverts hand-made corrections --
    # most damagingly the five-argument s32 sub_GAME_7F0B7F84, which the patch changed from
    # the upstream four-argument void form. Reverting it stops src/game/bg.c compiling and
    # the link then fails with about thirty undefined bg* symbols, none of which name this
    # header. That cost a full clean-build cycle to diagnose once; refuse by default.
    if os.path.exists(OUT) and '--force' not in sys.argv:
        with io.open(OUT, encoding='utf-8', errors='surrogateescape') as fh:
            existing = fh.read()
        if 'sub_GAME_7F0B7F84(s32 value' in existing:
            sys.exit(
                "%s already holds the curated header from 0001-source.patch.\n"
                "Regenerating would revert it and break src/game/bg.c. This tool is for\n"
                "adding declarations during development, not a build step -- see\n"
                "docs/SETUP.md section 3.5. Pass --force if you really mean to.\n" % OUT)

    names = undeclared_names()
    print('implicitly-declared functions found: %d' % len(names))
    protos = sorted(extract(names).values())
    print('prototypes extracted: %d' % len(protos))

    hdrs = game_headers()
    # Drop anything that still will not compile, so the header is always usable.
    for _ in range(15):
        write(hdrs, protos)
        r = subprocess.run(['clang'] + FLAGS + ['-x', 'c', OUT], capture_output=True, text=True)
        errs = r.stdout + r.stderr
        if 'error:' not in errs:
            print('header compiles clean: %d headers, %d prototypes' % (len(hdrs), len(protos)))
            return
        blamed = set(re.findall(r'src/game/([A-Za-z0-9_]+\.h):\d+:\d+: error:', errs))
        if blamed:
            hdrs = [h for h in hdrs if os.path.basename(h) not in blamed]
            print('dropped non-self-contained headers: %s' % ', '.join(sorted(blamed)))
            continue
        bad = set(re.findall(r"unknown type name '([A-Za-z0-9_]+)'", errs))
        lines = {int(n) for n in re.findall(r'ge_port_decls\.h:(\d+):', errs)}
        cur = io.open(OUT, encoding='utf-8', errors='surrogateescape').read().split('\n')
        drop = {cur[i - 1] for i in lines if 0 < i <= len(cur)}
        before = len(protos)
        protos = [p for p in protos
                  if p not in drop and not any(re.search(r'\b%s\b' % b, p) for b in bad)]
        if len(protos) == before:
            print('stuck; remaining errors:')
            print('\n'.join(l for l in errs.split('\n') if 'error:' in l)[:800])
            return
    print('did not converge')


if __name__ == '__main__':
    main()
