#!/usr/bin/env python3
"""Turn a raw RGBA dump into a C header the port can hand straight to SDL.

SDL2 built without SDL_image cannot read a PNG, and adding an image library to decode one 128px
icon would be a poor trade. The pixels travel as a byte array instead, so the binary carries its
own icon rather than looking for a file next to itself -- which is what makes the icon survive
being copied somewhere else, which is how people actually move builds around.

Usage: rgba_to_header.py <file.rgba> <size> <out.h>
"""
import sys


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    src, size, dst = sys.argv[1], int(sys.argv[2]), sys.argv[3]

    with open(src, "rb") as fh:
        data = fh.read()

    want = size * size * 4
    if len(data) != want:
        sys.exit("expected %d bytes for %dx%d RGBA, got %d" % (want, size, size, len(data)))

    with open(dst, "w", encoding="utf-8") as out:
        out.write(
            "/* The launcher icon, as pixels.\n"
            " *\n"
            " * Generated by tools/make_icons.sh from assets/icon/goldeneye-plus-transparent.png.\n"
            " * Do not edit by hand -- change the source PNG and run the script again.\n"
            " *\n"
            " * %dx%d RGBA, row-major, top row first, which is the layout SDL_CreateRGBSurfaceFrom\n"
            " * expects with a pitch of width * 4.\n"
            " */\n"
            "#ifndef GE_ICON_H\n"
            "#define GE_ICON_H\n\n"
            "#define GE_ICON_SIZE %d\n\n"
            "static const unsigned char ge_icon_rgba[%d] = {\n" % (size, size, size, want))
        for i in range(0, want, 16):
            row = ", ".join("0x%02x" % b for b in data[i:i + 16])
            out.write("    %s,\n" % row)
        out.write("};\n\n#endif /* GE_ICON_H */\n")

    print("wrote %s (%d bytes of pixels)" % (dst, want))


if __name__ == "__main__":
    main()
